### ISSUE TITLE
client side crashed 

### ISSUE THREAD

**Issue by Mysterizon** [PaleoCrafter/VanillaImmersion#8] opened 2016-08-04 06:18 UTC
on client side, my minecraft game crashed when i used tools to break one of the table such as furnace (with pickaxe) or crafting table (with axe).

when i am about to break them.. it caused my client side to crash. and here's the crash report: 

http://pastebin.com/mMjqJR6L

EDIT: there is one more thing that i dont realize.. it has to do with rendering entity and it caused the crash.. i was using a shader, "Continuum Shader 1.3 Preview 2". i will run one more test without the shader to see if it doesn't cause the crashing. 

EDIT 1: its confirmed that shader is related to rendering Entity and its what caused the crashing. 

EDIT 2: now its not just me, even Creeper blow up and it also breaking the tables that cause the crashing as well.

**Comment by PaleoCrafter** [comment] 2016-09-03 16:51
This appears to be a duplicate of #5 and hence will be closed. Should be adressed with the first version for 1.10.2.

**Closed by PaleoCrafter** 2016-09-03 16:51 UTC
Labels: duplicate
