### ISSUE TITLE
Textures missing

### ISSUE THREAD

**Issue by davqvist** [PaleoCrafter/VanillaImmersion#14] opened 2017-07-21 21:08 UTC
MC 1.12
Forge 2420
Vanilla Immersion 1.1.2.4

Crafting Table and Furnace textures are missing when placing them, making the blocks (and therefore the pack) unplayable. Using F3+T makes the textures visible again, but the blocks don't work as intended. Tested in SP and MP.

**Comment by PaleoCrafter** [comment] 2017-07-21 21:19
Hm... Haven't heard of that yet. So this is observable in singleplayer as well? Models showing up as missing in multiplayer is a well known Forge issue that - I hope - will get fixed soon. Are you only playing with my mod and if not, could you provide me with a list of the other mods,

**Comment by davqvist** [comment] 2017-07-21 22:25
I said in OP that in doesn't work in SP and in MP. I tested like a few days ago where it still worked, so it must be a mod or Forge update causing it.

Directory output:
https://pastebin.com/1shVcupE

**Comment by PaleoCrafter** [comment] 2017-07-22 17:35
I definitely can't reproduce this with just latest Forge and my mod. Did you only update Forge and Vanilla Immersion before this issue occurred or was another mod also affected? I did not introduce any changes lately that would mess around with rendering.

**Comment by PaleoCrafter** [comment] 2017-07-22 17:58
Hm... I've noticed that starting a singleplayer session after multiplayer will also cause the models to miss. Does the bug occur for you even if you directly join a singleplayer world and don't try multiplayer first?

**Comment by Akitori** [comment] 2017-07-22 23:22
similar bug, occurred on multiplayer with guis unusable, however going to singleplayer has the models working fine.

**Comment by PaleoCrafter** [comment] 2017-07-22 23:25
@Akitori: The way I replace the Vanilla blocks with my own (which is the official way) is currently broken for dedicated servers, unfortunately. It is a well known problem and I'm in contact with the Forge devs in order to solve it.

**Comment by Akitori** [comment] 2017-07-22 23:27
couldn't you instead make your immersive version a separate block and instead have the immersive blocks take over vanilla recipes?

**Comment by PaleoCrafter** [comment] 2017-07-22 23:35
While that technically is possible (and is in fact how the mod used to work), it is not particular desirable. Simply replacing the recipes, drops etc. will still not make the Vanilla blocks completely unobtainable. Getting overrides fixed is the right way to do this and hopefully won't take long anymore :)

**Comment by Akitori** [comment] 2017-07-22 23:43
ah alright. any chance of that perhaps being a option in the future? as that relates to a feature i shall end that here.

**Comment by davqvist** [comment] 2017-07-23 18:28
Yeah, seems to only happen if you join a server first and then go to SP. If you go to SP first, it seems to work.

**Comment by PaleoCrafter** [comment] 2017-07-23 18:42
I've submitted the PR MinecraftForge/MinecraftForge#4224 to Forge, which should resolve this issue for instances where both the client and server have Vanilla Immersion installed. Investigating this also has brought to my attention that I need to disable my event handlers when connecting to a server without the mod.

**Comment by PaleoCrafter** [comment] 2017-07-28 19:53
Fixed as of Forge 14.21.1.2426.

**Closed by PaleoCrafter** 2017-07-28 19:53 UTC
Labels: bug, compatibility

**Comment by davqvist** [comment] 2017-07-29 05:34
Confirmed, thanks a lot.
