### ISSUE TITLE
Crash with Crafting Table

### ISSUE THREAD

**Issue by Kevun1** [PaleoCrafter/VanillaImmersion#25] opened 2017-11-28 23:05 UTC
Forge v2545

Log: https://pastebin.com/0QQ3Sy64

When I right clicked the crafting table with one item in it, (I might have been sneaking, I don't remember), the game crashed.

**Comment by marvin-roesch** [comment] 2017-12-27 15:51
Sorry for only reacting now, but could you provide any way of reproducing this issue? That exception should only occur when the crafting table wasn't properly initialized in the first place (which it obviously was, since you had a block in it).

**Comment by marvin-roesch** [comment] 2018-02-10 11:32
Should be fixed as of commit 05959578b43144a06a1d5df0f9fe28a9e2d2c163, forgot to close it.

**Closed as completed by marvin-roesch** 2018-02-10 11:32 UTC
Labels: bug
